import { Injectable } from '@nestjs/common';
import { createReadStream } from 'node:fs';
import { access, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import type { OdcStorage } from './odc-storage';

const DEFAULT_UPLOAD_DIR = 'var/odc-uploads';

// RC-33 — the only OdcStorage implementation in this RC: files land under
// ODC_UPLOAD_DIR (default var/odc-uploads), one file per storage key, key
// segments becoming real subdirectories. Every key this ever receives is
// server-generated by buildOdcStorageKey() (organizationId/applicationId/
// documentId/uuid.ext) — never client input — but resolve() still refuses
// to write or read outside its own root, as a second, independent guard
// against a key ever escaping it.
@Injectable()
export class LocalOdcStorage implements OdcStorage {
  private readonly root: string;

  constructor() {
    this.root = resolve(process.env.ODC_UPLOAD_DIR ?? DEFAULT_UPLOAD_DIR);
  }

  async put(key: string, data: Buffer): Promise<void> {
    const filePath = this.resolveWithinRoot(key);
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, data);
  }

  async exists(key: string): Promise<boolean> {
    try {
      await access(this.resolveWithinRoot(key));
      return true;
    } catch {
      return false;
    }
  }

  async get(key: string): Promise<NodeJS.ReadableStream | null> {
    if (!(await this.exists(key))) {
      return null;
    }
    return createReadStream(this.resolveWithinRoot(key));
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolveWithinRoot(key), { force: true });
  }

  private resolveWithinRoot(key: string): string {
    const filePath = resolve(this.root, key);
    if (filePath !== this.root && !filePath.startsWith(this.root + sep)) {
      throw new Error(
        `Refusing to resolve a storage key outside the upload root: "${key}"`,
      );
    }
    return filePath;
  }
}
