import {
  buildOdcStorageKey,
  extensionForMimeType,
  sanitizeContentDispositionFilename,
  storageKeyBelongsTo,
} from './odc-storage-key';

describe('extensionForMimeType', () => {
  it('maps known MIME types to their real extension', () => {
    expect(extensionForMimeType('application/pdf')).toBe('.pdf');
    expect(extensionForMimeType('image/png')).toBe('.png');
    expect(extensionForMimeType('image/jpeg')).toBe('.jpg');
  });

  it('derives a safe extension from an unknown but short MIME type instead of trusting client input', () => {
    expect(extensionForMimeType('application/msword')).toBe('.msword');
  });

  it('caps a long, unknown MIME subtype instead of producing an unbounded extension', () => {
    expect(extensionForMimeType('application/octet-stream')).toBe(
      '.octetstrea',
    );
    expect(
      extensionForMimeType('application/octet-stream').length,
    ).toBeLessThanOrEqual(11);
  });

  it('never produces an extension containing a path separator or dot from the MIME type itself', () => {
    const ext = extensionForMimeType('application/x-evil/../../etc');
    expect(ext).not.toMatch(/[./\\]{2,}/);
  });
});

describe('buildOdcStorageKey', () => {
  it('is scoped to organizationId/applicationId/documentId and never includes client input', () => {
    const key = buildOdcStorageKey(
      'org-1',
      'app-1',
      'doc-1',
      'application/pdf',
    );
    expect(key.startsWith('org-1/app-1/doc-1/')).toBe(true);
    expect(key.endsWith('.pdf')).toBe(true);
  });

  it('never produces the same key twice for the same document', () => {
    const first = buildOdcStorageKey(
      'org-1',
      'app-1',
      'doc-1',
      'application/pdf',
    );
    const second = buildOdcStorageKey(
      'org-1',
      'app-1',
      'doc-1',
      'application/pdf',
    );
    expect(first).not.toBe(second);
  });
});

describe('storageKeyBelongsTo (Codex review — traversal hardening)', () => {
  it('accepts a real key generated by buildOdcStorageKey() for its own triplet', () => {
    const key = buildOdcStorageKey(
      'org-1',
      'app-1',
      'doc-1',
      'application/pdf',
    );
    expect(storageKeyBelongsTo(key, 'org-1', 'app-1', 'doc-1')).toBe(true);
  });

  it('rejects a canonical-looking key belonging to a different organization/application/document', () => {
    const key = buildOdcStorageKey(
      'org-1',
      'app-1',
      'doc-1',
      'application/pdf',
    );
    expect(storageKeyBelongsTo(key, 'org-2', 'app-1', 'doc-1')).toBe(false);
    expect(storageKeyBelongsTo(key, 'org-1', 'app-2', 'doc-1')).toBe(false);
    expect(storageKeyBelongsTo(key, 'org-1', 'app-1', 'doc-2')).toBe(false);
  });

  // The exact scenario the review flagged: `startsWith(prefix)` accepts
  // this because the string literally starts with the expected prefix,
  // but path.resolve() (used by LocalOdcStorage.resolveWithinRoot())
  // normalizes the embedded `..` segments and walks straight out to a
  // completely different organization/application/document — never
  // leaving the overall storage root, so the root-boundary check alone
  // never catches it either.
  it('rejects a traversal key that only superficially starts with the expected prefix', () => {
    const traversal = 'org-1/app-1/doc-1/../../../org-2/app-2/doc-2/secret.pdf';
    expect(storageKeyBelongsTo(traversal, 'org-1', 'app-1', 'doc-1')).toBe(
      false,
    );
  });

  it('rejects every other traversal/encoding variant', () => {
    const cases = [
      // Leading traversal / absolute-path-like.
      '../org-1/app-1/doc-1/uuid.pdf',
      '/org-1/app-1/doc-1/uuid.pdf',
      // A bare `.` or `..` segment anywhere, not just at the start.
      'org-1/app-1/doc-1/./uuid.pdf',
      'org-1/./app-1/doc-1/uuid.pdf',
      // Doubled/trailing slash producing an empty segment.
      'org-1//app-1/doc-1/uuid.pdf',
      'org-1/app-1/doc-1/uuid.pdf/',
      // Backslash-based traversal (never even segmented on `/`).
      'org-1/app-1/doc-1\\..\\..\\org-2\\secret.pdf',
      // An embedded NUL.
      'org-1/app-1/doc-1/uuid.pdf\0.jpg',
      // A correct prefix but one extra segment after the filename.
      'org-1/app-1/doc-1/uuid.pdf/extra',
      // A correct prefix but a filename that isn't the UUID(+ext) shape
      // buildOdcStorageKey() actually generates — never trusted just
      // because the first three segments match.
      'org-1/app-1/doc-1/secret.pdf',
      // Empty string.
      '',
    ];
    for (const key of cases) {
      expect(storageKeyBelongsTo(key, 'org-1', 'app-1', 'doc-1')).toBe(false);
    }
  });

  it('accepts a canonical key with no extension (a mimeType extensionForMimeType could not derive one from)', () => {
    const uuid = buildOdcStorageKey('org-1', 'app-1', 'doc-1', 'a/')
      .split('/')
      .pop() as string;
    // extensionForMimeType('a/') derives '' (empty subtype after
    // stripping non-alphanumerics), so this key has no extension at all —
    // still canonical.
    expect(uuid.includes('.')).toBe(false);
    const key = `org-1/app-1/doc-1/${uuid}`;
    expect(storageKeyBelongsTo(key, 'org-1', 'app-1', 'doc-1')).toBe(true);
  });
});

describe('sanitizeContentDispositionFilename', () => {
  it('keeps an ordinary filename unchanged', () => {
    expect(sanitizeContentDispositionFilename('cv-fitia.pdf')).toBe(
      'cv-fitia.pdf',
    );
  });

  it('strips characters that could inject a header or break out of the quoted value', () => {
    const malicious = 'cv.pdf"\r\nX-Injected: 1\\';
    const sanitized = sanitizeContentDispositionFilename(malicious);
    expect(sanitized).not.toMatch(/[\r\n"\\]/);
  });

  it('falls back to a safe default when nothing legible survives sanitization', () => {
    expect(sanitizeContentDispositionFilename('\r\n')).toBe('document');
  });
});
