// RC-33 — pure, deterministic helpers around the ODC upload storage key and
// download filename. Nothing here touches the filesystem or the network:
// this module only answers "what key/extension/filename string should this
// produce", the same "pure logic, tested in isolation" posture as
// odc-completeness.ts.

import { randomUUID } from 'node:crypto';

// Only the MIME types any OdcDocumentType.mimeAllow actually names today
// (see prisma/schema.prisma's default and every seed/example) get a real
// extension. Anything else still gets a safe, storage-key-legal extension
// derived from its own subtype — never from the client's originalName, which
// is never trusted as part of a server-emitted storage key.
const KNOWN_EXTENSIONS: Record<string, string> = {
  'application/pdf': '.pdf',
  'image/png': '.png',
  'image/jpeg': '.jpg',
};

export function extensionForMimeType(mimeType: string): string {
  const known = KNOWN_EXTENSIONS[mimeType];
  if (known) return known;
  const subtype = mimeType
    .split('/')[1]
    ?.replace(/[^a-z0-9]/gi, '')
    .slice(0, 10);
  return subtype ? `.${subtype.toLowerCase()}` : '';
}

// {organizationId}/{applicationId}/{documentId}/{uuid}{ext} — every segment
// is a server-known id (never client input), so this can never be steered
// outside its own organization/application/document prefix. `documentId` is
// generated by the caller *before* this is called and reused as the
// OdcDocument row's own `id` on create, so the two always match; the
// trailing uuid exists purely so two uploads for the same document id can
// never collide on disk (defensive — today's flow only ever calls this once
// per generated documentId).
export function buildOdcStorageKey(
  organizationId: string,
  applicationId: string,
  documentId: string,
  mimeType: string,
): string {
  return `${organizationId}/${applicationId}/${documentId}/${randomUUID()}${extensionForMimeType(mimeType)}`;
}

// A Content-Disposition filename is attacker-influenced (it round-trips the
// candidate's own uploaded originalName) and sits inside an HTTP header, so
// CR/LF (header injection), the quote that closes the filename="..." value,
// and backslashes are stripped entirely rather than substituted — a
// placeholder character would still make an all-control-character name look
// legible when it isn't. Everything else in the original name is kept —
// this only needs to be safe, not ASCII-only.
const UNSAFE_FILENAME_CHARACTERS = /[\r\n"\\]/g;

export function sanitizeContentDispositionFilename(
  originalName: string,
): string {
  const sanitized = originalName.replace(UNSAFE_FILENAME_CHARACTERS, '').trim();
  return sanitized.length > 0 ? sanitized : 'document';
}
